<?php

/*BASE DE DADOS

    PAISES: 
        ✅ MEDALHA_2020 = INT 
        ✅ MEDALHA_2016 = INT
        ✅ VARIACAO = %
        ✅ COR = STRING
        %_RELATIVA = %
        ALTURA = INT
        LARGURA = INT
        X = INT
        Y = INT

//  ✅DEFINIR COR
        PERCORRER PAISES
            COMPARAR 2020 COM 2016 E DEFINIR COR

//  DEFINIR TAMANHO E POSIÇÃO
    ✅1.DEFINIR AREA:
        ✅ALTURA   = INT
        ✅LARGURA  = INT
        ✅X_INICIO = INT
        ✅Y_INICIO = INT

    ✅2.ORDENAR PAISES DO MAIOR AO MENOR USANDO MEDALHA_2020
    ✅3.SOMAR TOTAL DE MEDALHAS
    ✅4.DEFINIR %_RELATIVA:
        MEDALHAS_RESTANTES = TOTAL MEDALHAS   
        PERCORRES PAISES:
            PAIS[%_RELATIVA] = (MEDALHAS_PAIS / MEDALHAS_RESTANTES)
            MEDALHAS_RESTANTES = (MEDALHAS_RESTANTES - MEDALHAS_PAIS)
            PROXIMO PAIS
 
    ✅5.DEFINIR TAMANHO & LOCALIZAÇÃO:
        ALTURA_DISPONIVEL
        LARGURA_DISPONIVEL
        X_DISPONIVEL
        Y_DISPONIVEL

        PERCORRER PAISES:
            PAIS[X] = X_DISPONIVEL 
            PAIS[Y] = Y_DISPONIVEL 
    
            IF(ALTURA_DISPONIVEL > LARGURA_DISPONIVEL)
                PAIS[LARGURA] = LARGURA_DISPONIVEL
                PAIS[ALTURA] = PAIS[%_RELATIVA] * ALTURA_DISPONIVEL
                ALTURA_DISPONIVEL = ALTURA_DISPONIVEL - PAIS[ALTURA]
                Y_DISPONIVEL = Y_DISPONIVEL + PAIS[ALTURA]

            IF(ALTURA_DISPONIVEL =< LARGURA_DISPONIVEL)
                PAIS[ALTURA] = ALTURA_DISPONIVEL
                PAIS[LARGURA] = PAIS[%_RELATIVA] * LARGURA_DISPONIVEL
                LARGURA_DISPONIVEL = LARGURA_DISPONIVEL - PAIS[LARGURA]
                X_DISPONIVEL = X_DISPONIVEL +  PAIS[LARGURA]
            
                






